### PR TITLE
[completes #53556821] refine test env by using guard, parallel tests, and zeus

### PR DESCRIPTION
**Pull request by jgrevich**
I think this is ready to go. Will you guys take a look and try this out?  Some important points, 1.) You'll need to create files from the .example files (`rake bootstrap:de_example bootstrap:setup_secret` can automate that step). 2.) If you're using parallel tests, you'll need to setup your DB env accordingly (see: https://github.com/grosser/parallel_tests#setup-for-rails). Guard, Parallel Tests, and Zeus seem to be getting along nicely for me.
# 

Commit description below:

Added database_cleaner gem to the :development, :test group to play
nice with Zeus. Alphabetized the listing of the gems in the dev
and test groups.

Added guard-livereload to automatically reload your browser window when
you modify and save a view file.

Added parallel_tests and integrated with Zeus.

Setup guard to work with Zeus/Parallel tests.

Added and removed some lines from the Guard file to make it more
appropriate to our use case.

Modified GC methodology with test suite to shave off a few seconds.

Fine-tuned zeus.json file and created an alias for zeus parallel_rspec

Ignore user customizable files and rename as .example

### CODE REVIEW

**Comment by arowla** [comment]
I had a couple of minor issues with this, possibly related to OSX/Linux incompatibilities and the bootstrap tasks, but I think we should probably put this one to bed for now and merge the pull request.

But for the record, when I ran the bootstrap tasks ala "rake bootstrap:de_example bootstrap:setup_secret", two things went wrong:
1. Guardfile.example did not get copied to Guardfile.
2. The secret didn't get populated (this was easily fixed by running "rake bootstrap:setup_secret" on its own).

**Comment by jgrevich** [comment]
Any other problems than what you found above?  If not, can you squash the commits and force update the branch so we can merge it into master?

**Comment by greggersh** [comment]
I think the only reason to have a .example file is if the non .example file has something in it specific to our environment (like a secret key or an IP address to a server).  Otherwise I don't feel bad about making decisions about how things should run.  Our project uses rspec so I don't think it's a bad thing to have a .rspec file.  I would say the same for all the .example files here...unless I'm missing something.

**Comment by jgrevich** [comment]
@greggersh I agree, the only reason I was thinking of .exampling those files was to provide a file that has most if not all of the options provided and something that does not force a specific setting.  I guess the latter reason doesn't really matter since we .gitignored those files. Previously it was a bit of a pain having to override the .rspec settings saved in the repo, esp. since it overrides a user's global rspec settings in ~/.rspec.

Can we merge this in if we convert the example files (.rspec, .zeus.json, custom_plan.rb, and Guardfile) back to regular files?

**Comment by greggersh** [comment]
I just reverted the .rspec file (with the changes from .example, feel free to add anything else you think appropriate), and left the others as .example files, as I'm not as familiar with what those things do.

**Pull request closed without merging**
