### PR TITLE
Updates return value of unique ID to 'uid'

### PR DESCRIPTION
**Pull request by amoose**
Per discussion with @greg we decided to keep UID references uniform.

See: https://github.com/GSA-OCSIT/omniauth-myusa/pull/1

### CODE REVIEW

**Comment by amoose** [comment]
@greggersh omniauth-mygov gem is still supported with these changes. no breakie

**Comment by amoose** [comment]
@greggersh Can I go ahead and manually merge this in? (squashing commits)

**Comment by greggersh** [comment]
Yep!

**Comment by jgrevich** [comment]
Can we trim off this branch if you merged locally?

**Comment by amoose** [comment]
done.

**Comment by amoose** [comment]
I closed the pull req, but never pushed the changes. Pushed today in c36b5a5b7b59a380a0b3ab060cd4f1711a63baa2

**Pull request closed without merging**
